
const Services = [
    {
        Id: '1',
        sImgS:'images/service-single/graphics/img-1.jpg',
        sTitle: '3% LP分红',
        description:'所有交易的 3% 交易税收 将分红给提供LBB流动性的共识者',
        des2:'Lacus, etiam sed est eu tempus need Temer diam congue laoret .',
        des3:'One way to categorize the activities is in terms of the professional’s area of expertise such as competitive analysis, corporate strategy the activities',
        icon:'flaticon-vector',
        ssImg1:'images/service-single/graphics/img-2.jpg',
        ssImg2:'images/service-single/graphics/img-3.jpg',
    },
    {
        Id: '2',
        sImgS:'images/service-single/brand/img-1.jpg',
        sTitle: '2% 回流',
        description:'所有交易的 2% 交易税收 将自动回流流动池，将会更加的稳定币价',
        des2:'Lacus, etiam sed est eu tempus need Temer diam congue laoret .',
        des3:'One way to categorize the activities is in terms of the professional’s area of expertise such as competitive analysis, corporate strategy the activities',
        icon:'flaticon-palette',
        ssImg1:'images/service-single/brand/img-2.jpg',
        ssImg2:'images/service-single/brand/img-3.jpg',
    },
    {
        Id: '3',
        sImgS:'images/service-single/ux/img-1.jpg',
        sTitle: '2% 营销',
        description:'所有交易的 2% 交易税收 将作为营销税收，进行代币回购与推广',
        des2:'Lacus, etiam sed est eu tempus need Temer diam congue laoret .',
        des3:'One way to categorize the activities is in terms of the professional’s area of expertise such as competitive analysis, corporate strategy the activities',
        icon:'flaticon-add',
        ssImg1:'images/service-single/ux/img-3.jpg',
        ssImg2:'images/service-single/ux/img-3.jpg',
    },
    {
        Id: '4',
        sImgS:'images/service-single/development/img-1.jpg',
        sTitle: '一代 6% 返佣',
        description:'一代邀请人 我们给予 6% USDT返佣 作为回馈，直接推广的人越多 赚得越多',
        des2:'Lacus, etiam sed est eu tempus need Temer diam congue laoret .',
        des3:'One way to categorize the activities is in terms of the professional’s area of expertise such as competitive analysis, corporate strategy the activities',
        icon:'flaticon-coding',
        ssImg1:'images/service-single/development/img-2.jpg',
        ssImg2:'images/service-single/development/img-3.jpg',
    },
    {
        Id: '5',
        sImgS:'images/service-single/app/img-1.jpg',
        sTitle: '二代 2% 返佣',
        description:'二代邀请人 我们给予 2% USDT返佣 作为回馈，间接推广的人越多 赚得越多',
        des2:'Lacus, etiam sed est eu tempus need Temer diam congue laoret .',
        des3:'One way to categorize the activities is in terms of the professional’s area of expertise such as competitive analysis, corporate strategy the activities',
        icon:'flaticon-app-development',
        ssImg1:'images/service-single/app/img-2.jpg',
        ssImg2:'images/service-single/app/img-3.jpg',
    },
    {
        Id: '6',
        sImgS:'images/service-single/softwere/img-1.jpg',
        sTitle: '三代 2% 返佣',
        description:'三代邀请人 我们给予 1% USDT返佣 作为回馈，间接推广的人越多 赚得越多',
        des2:'Lacus, etiam sed est eu tempus need Temer diam congue laoret .',
        des3:'One way to categorize the activities is in terms of the professional’s area of expertise such as competitive analysis, corporate strategy the activities',
        icon:'flaticon-smartphone',
        ssImg1:'images/service-single/softwere/img-2.jpg',
        ssImg2:'images/service-single/softwere/img-3.jpg',
    },
    {
        Id: '7',
        sImgS:'images/service-single/sm/img-1.jpg',
        sTitle: '50 USDT 参与',
        description:'以 50 USDT 的额度进行 IDO，成为LBB联盟的一员',
        des2:'Lacus, etiam sed est eu tempus need Temer diam congue laoret .',
        des3:'One way to categorize the activities is in terms of the professional’s area of expertise such as competitive analysis, corporate strategy the activities',
        icon:'flaticon-social-media',
        ssImg1:'images/service-single/sm/img-2.jpg',
        ssImg2:'images/service-single/sm/img-3.jpg',
    },
    {
        Id: '8',
        sImgS:'images/service-single/dm/img-1.jpg',
        sTitle: '100 USDT 额度',
        description:'以 100 USDT 的额度进行 IDO，成为LBB联盟的一员',
        des2:'Lacus, etiam sed est eu tempus need Temer diam congue laoret .',
        des3:'One way to categorize the activities is in terms of the professional’s area of expertise such as competitive analysis, corporate strategy the activities',
        icon:'flaticon-promotion',
        ssImg1:'images/service-single/dm/img-2.jpg',
        ssImg2:'images/service-single/dm/img-3.jpg',
    },
    {
        Id: '9',
        sImgS:'images/service-single/email/img-1.jpg',
        sTitle: '专属邀请连结',
        description:'使用专属邀请连结 来邀请好友进行IDO，为联盟做出贡献',
        des2:'Lacus, etiam sed est eu tempus need Temer diam congue laoret .',
        des3:'One way to categorize the activities is in terms of the professional’s area of expertise such as competitive analysis, corporate strategy the activities',
        icon:'flaticon-email-marketing',
        ssImg1:'images/service-single/email/img-2.jpg',
        ssImg2:'images/service-single/email/img-3.jpg',
    },
]    

export default Services;